### ISSUE TITLE
Delete a Review

### ISSUE THREAD

**Issue by lainey1** [lainey1/homeAway#17]
Delete an existing review.

- [x]  An authenticated user is required for a successful response
- [x]  Only the owner of the review is authorized to delete
- [x]  Review record is removed from the database after request
- [x]  Success response includes a message indicating a successful deletion
- [x]  Error response with status 404 is given when a spot does not exist with the provided id

**Comment by Mila7158** [comment]
still doesn't work in production

**Comment by Mila7158** [comment]
pushed it to dev

**Comment by lainey1** [comment]
cleaned up associations during prod deployment this morning. Working now in prod :)
